const layerSectionObjects = [
    {
      id: "manahatta_items",
      caretId: "manahatta-layer-caret",
      label: "1609 | Manahatta",
      itemSelector: ".manahatta_layer_item",
      zoomTo: "Manhattan",
      infoId: "manahatta-info",
      type: "group",
    },
    {
      id: "lenape_trails",
      name: "lenape_trails",
      label: "Lenape Trails",
      iconColor: "#ff0000",
      className: "manahatta",
      topLayerClass: "manahatta_layer",
      isSolid: true
    },
    {
      id: "manahatta_shoreline",
      name: "manahatta_shoreline",
      className: "manahatta",
      label: "Manahatta Shoreline",
      iconColor: "#ffd700",
      topLayerClass: "manahatta_layer",
      isSolid: true
    },
    {
      id: "manahatta_streams",
      name: "manahatta_streams",
      label: "Streams (c 1600)",
      className: "manahatta",
      iconColor: "#0000ff",
      topLayerClass: "manahatta_layer",
      isSolid: true
    },
    {
      id: "farms_layer_items",
      caretId: "farms-layer-caret",
      label: "1638-83 | Original Grants & Farms",
      itemSelector: ".farms_layer_item",
      zoomTo: "Original Grants",
      infoId: "farms-info-layer",
      type: "group",
    },
    {
      id: "farms_layer",
      className: "farms_layer",
      name: "farms_layer",
      iconColor: "#e3ed58",
      label: "Information",
      topLayerClass: "farms_layer",
      iconType: "square",
      isSolid: true
    },
    {
      id: "farms_layer_lines",
      className: "farms_layer",
      name: "farms_layer_lines",
      iconColor: "#ff0000",
      label: "Lines",
      topLayerClass: "farms_layer",
      iconType: "square",
      isSolid: false
    },
    {
      id: "grants_layer_items",
      caretId: "dutch-grants-layer-caret",
      label: "1640-64 | Dutch Grants",
      itemSelector: ".dutch_grants_layer_item",
      zoomTo: "NA",
      infoId: "grants-info-layer",
      type: "group",
    },
    {
      id: "grants_layer",
      className: "grants_layer",
      name: "grants_layer",
      iconColor: "#e3ed58",
      label: "Information",
      topLayerClass: "dutch_grants_layer",
      iconType: "square",
      isSolid: true
    },
    {
      id: "grants_layer_lines",
      className: "grants_layer",
      name: "grants_layer_lines",
      iconColor: "#ff0000",
      label: "Lines",
      topLayerClass: "dutch_grants_layer",
      iconType: "square",
      isSolid: false
    },
    {
      id: "circle_point",
      name: "circle_point",
      checked: true,
      label: "1643-75 | Lot Events",
      iconColor: "#097911",
      zoomTo: "NA",
      infoId: "demo-taxlot-info-layer",
      type: "lots-events",
    },
    {
      id: "grant_lots",
      name: "grant_lots",
      label: "1643-67 | Demo Grant Divisions: C7",
      iconColor: "#008888",
      zoomTo: "NA",
      infoId: "demo-grant-info-layer",
      type: "grants-lots",
    },
    {
      id: "castello_points",
      name: "castello_points",
      label: "1660 | Castello Taxlots",
      iconColor: "#ff0000",
      zoomTo: "NA",
      infoId: "castello-info-layer",
      type: "castello-points",
    },
    {
      id: "current_lots_items",
      caretId: "current-lots-layer-caret",
      label: "Current Lots",
      itemSelector: ".current_lots_layer_item",
      zoomTo: "NA",
      infoId: "current-lots-info-layer",
      type: "group",
    },
    {
      className: "current_lots",
      id: "current_lots",
      name: "current_lots",
      iconColor: "#7b68ee",
      label: "Information",
      topLayerClass: "current_lots_layer",
      isSolid: true,
      iconType: "square"
    },
    {
      className: "current_lots",
      id: "current_lots_lines",
      name: "current_lots_lines",
      iconColor: "#000080",
      label: "Lines",
      topLayerClass: "current_lots_layer",
      iconType: "square",
      isSolid: false
    },
    {
      className: 'current_buildings',
      id: 'current_buildings_lines',
      name: 'current_buildings_lines',
      iconColor: '#0000ff',
      label: 'Current Buildings',
      zoomTo: 'NA',
      infoId: 'current-buildings-lines-info-layer',
      type: "current-buildings"
    }
  ];